import { RouteInfo } from "./sidebar.metadata";

export const ROUTES: RouteInfo[] = [
  {
    path: "/admin/dashboard",
    title: "Dashboard",
    icon: "bi bi-pie-chart-fill",
    className: "",
    extralink: true,
    submenu: [],
    role: ["StaffAdmin"],
  },
  {
    path: "/admin/nov",
    title: "Citations",
    icon: "bi bi-journal-text",
    className: "",
    extralink: true,
    submenu: [],
    role: ["StaffAdmin", "Issuer", "AuthSigner", "TSA User", "Superadmin"],
  },
  {
    path: "/admin/inspection",
    title: "Inspections",
    icon: "bi bi-file-text",
    className: "",
    extralink: true,
    submenu: [],
    role: ["StaffAdmin", "Issuer", "Superadmin", "Security", "TSA User"],
  },
  {
    path: "/admin/incident",
    title: "Incidents",
    icon: "bi bi-journals",
    className: "",
    extralink: true,
    submenu: [],
    role: ["Issuer", "StaffAdmin", "Superadmin", "Security", "TSA User"],
  },
  {
    path: "/admin",
    title: "Badging",
    icon: "bi bi-person-badge",
    className: "has-arrow",
    extralink: true,
    submenu: [
      {
        path: "/admin/pendingbadgeapplicants",
        title: "Security Clearances",
        icon: "bi bi-caret-right",
        className: "",
        extralink: true,
        submenu: [],
        role: ["StaffAdmin", "Issuer", "AuthSigner", "Superadmin"],
      },
      {
        path: "/admin/pendingbadgeapplicants",
        title: "Security Clearances",
        icon: "bi bi-caret-right",
        className: "",
        extralink: true,
        submenu: [],
        role: ["Security"],
      },
      {
        path: "/admin/badgeverification",
        title: "Badge Verification",
        icon: "bi bi-caret-right",
        className: "",
        extralink: true,
        submenu: [],
        role: [
          "Tenant",
          "Security",
          "StaffAdmin",
          "Issuer",
          "AuthSigner",
          "TSA User",
          "Superadmin",
        ],
      },
      // {
      //   path: "/admin/badgedetails",
      //   title: "Badge Details",
      //   icon: "bi bi-caret-right",
      //   className: "",
      //   extralink: true,
      //   submenu: [],
      //   role: [
      //     "Tenant",
      //     "Security",
      //     "StaffAdmin",
      //     "Issuer",
      //     "AuthSigner",
      //     "TSA User",
      //     "Superadmin",
      //   ],
      // },
      {
        path: "/admin/badgelisting",
        title: "Badge Accountability Audit",
        icon: "bi bi-caret-right",
        className: "",
        extralink: false,
        submenu: [],
        role: ["StaffAdmin", "AuthSigner"],
      },
      {
        path: "/admin/activebadges",
        title: "Active Badges ",
        icon: "bi bi-caret-right",
        className: "",
        extralink: true,
        submenu: [],
        role: ["StaffAdmin", "AuthSigner"],
      },
    ],
    role: [
      "StaffAdmin",
      "Issuer",
      "AuthSigner",
      "Tenant",
      "Superadmin",
      "Security",
      "TSA User",
    ],
  },
  {
  path: "/admin",
  title: "Concessions Security",
  icon: "bi bi-journal-text",
  className: "has-arrow",
  extralink: true,
  submenu: [
    {
      path: "/admin/prohibiteditemmaster",
      title: "Prohibited Item Log",
      icon: "bi bi-journal-text",
      className: "",
      extralink: true,
      submenu: [],
      role: ["StaffAdmin", "AuthSigner", "Superadmin", "Concessionaire User"],
      
    },
    {
      path: "/admin/prohibitedcheckout",
      title: "Prohibited Item CheckOut",
      icon: "bi bi-caret-right",
      className: "",
      extralink: true,
      submenu: [],
      role: ["AuthSigner", "StaffAdmin", "Concessionaire User"],
      
    },
    {
      path: "/admin/concessionssecurity",
      title: "Prohibited Item Audit",
      icon: "bi bi-journal-text",
      className: "",
      extralink: true,
      submenu: [],
      role: ["StaffAdmin", "AuthSigner", "Concessionaire User"],
    
    },
    {
      path: "/admin/concessionssecurityauditlog",
      title: "PI Audit History",
      icon: "bi bi-journals",
      className: "",
      extralink: true,
      submenu: [],
      role: [ "AuthSigner"],
    
    },
  ],
  role: ["StaffAdmin", "AuthSigner", "Superadmin", "Concessionaire User"],
},
 {
    path: "/admin/testmacrolist",
    title: "AWS Schedule Old",
    icon: "bi bi-file-excel",
    className: "",
    extralink: true,
    submenu: [],
    role: [
      "Superadmin"
      
    ],
  },
  {
    path: "/admin/schedulerList",
    title: "AWS Schedule",
    icon: "bi bi-file-excel",
    className: "",
    extralink: true,
    submenu: [],
    role: [
      "Superadmin",
      "TSA User",
      "AWS Scheduler",
      "StaffAdmin",
      "TSA Approver",
      "Security",
      "Issuer",
      
    ],
  },
  {
    path: "/admin/referenceguides",
    title: "References",
    icon: "bi bi-journals",
    className: "",
    extralink: true,
    submenu: [],
    role: [
      "Tenant",
      "StaffAdmin",
      "Issuer",
      "AuthSigner",
      "TSA User",
      "Security",
      "Superadmin",
    ],
  },
  
  {
    path: "/admin/auditlog",
    title: "Audit Log",
    icon: "bi bi-journal",
    className: "",
    extralink: true,
    submenu: [],
    role: ["StaffAdmin"],
  },
  {
    path: "/admin/queryanalyzer",
    title: "Query Manager",
    icon: "bi bi-journal-text",
    className: "",
    extralink: true,
    submenu: [],
    role: ["StaffAdmin", "Superadmin"],
  },
  // {
  //   path: "/admin/concessionssecurity ",
  //   title: "Concessions Security ",
  //   icon: "bi bi-journal-text",
  //   className: "",
  //   extralink: true,
  //   submenu: [],
  //   role: ["StaffAdmin", "Superadmin"],
  // },
 
  // {
  //   path: "/admin/prohibiteditemmaster",
  //   title: "Prohibited Item Listing",
  //   icon: "bi bi-journal-text",
  //   className: "",
  //   extralink: true,
  //   submenu: [],
  //   role: ["StaffAdmin", "AuthSigner", "Superadmin"],
  // },
  //   {
  //   path: "/admin/concessionssecurity",
  //   title: "Concession Security",
  //   icon: "bi bi-journal-text",
  //   className: "",
  //   extralink: true,
  //   submenu: [],
  //   role: ["StaffAdmin", "AuthSigner"],
  // },
  // concessionssecurity
  // {
  //   path: "/admin/prohibiteditemmaster",
  //   title: "Prohibited Item Listing",
  //   icon: "bi bi-journal-text",
  //   className: "",
  //   extralink: true,
  //   submenu: [],
  //   role: ["StaffAdmin", "AuthSigner", "Superadmin"],
  // },

  // {
  //   path: "/admin",
  //   title: "Prohibited Items",
  //   icon: "bi bi-journal-text",
  //   className: "has-arrow",
  //   extralink: true,
  //   submenu: [
  //     {
  //       path: "/admin/prohibiteditemmaster",
  //       title: "Prohibited Item Log",
  //       icon: "bi bi-journal-text",
  //       className: "",
  //       extralink: true,
  //       submenu: [],
  //       role: ["StaffAdmin", "AuthSigner", "Superadmin" ,"Concessionaire User"],
  //     },
  //     {
  //       path: "/admin/prohibitedcheckout",
  //       title: "Prohibited Item CheckOut",
  //       icon: "bi bi-caret-right",
  //       className: "",
  //       extralink: true,
  //       submenu: [],
  //       role: [  "AuthSigner" , "StaffAdmin","Concessionaire User"],
  //     },
  //     {
  //       path: "/admin/concessionssecurity",
  //       title: "Prohibited Item Audit",
  //       icon: "bi bi-journal-text",
  //       className: "",
  //       extralink: true,
  //       submenu: [],
  //       role: [ "StaffAdmin", "AuthSigner","Concessionaire User"],
  //     },
  //   ], role: ["StaffAdmin",  "AuthSigner", "Superadmin","Concessionaire User"],
  //   },

  

  {
    path: "/admin",
    title: "Settings",
    icon: "bi bi-gear",
    className: "has-arrow",
    extralink: true,
    submenu: [
      {
        path: "/admin/badgereportsettingslist",
        title: "Badge Report",
        icon: "bi bi-caret-right",
        className: "",
        extralink: true,
        submenu: [],
        role: ["StaffAdmin", "Superadmin"],
      },
      {
        path: "/admin/concessionairesecurity",
        title: "Concessions Security",
        icon: "bi bi-caret-right",
        className: "",
        extralink: true,
        submenu: [],
        role: ["StaffAdmin",  "Superadmin"],
      },

      {
        path: "/admin/citationreason",
        title: "Citation Reason",
        icon: "bi bi-caret-right",
        className: "",
        extralink: true,
        submenu: [],
        role: ["StaffAdmin", "Superadmin"],
      },
      {
        path: "/admin/company",
        title: "Company",
        icon: "bi bi-caret-right",
        className: "",
        extralink: true,
        submenu: [],
        role: ["StaffAdmin", "Superadmin"],
      },
      {
        path: "/admin/remedialtraining",
        title: "Corrective Action",
        icon: "bi bi-caret-right",
        className: "",
        extralink: true,
        submenu: [],
        role: ["StaffAdmin", "Superadmin"],
      },

      {
        path: "/admin/location",
        title: "Doors-Gates",
        icon: "bi bi-caret-right",
        className: "",
        extralink: true,
        submenu: [],
        role: ["StaffAdmin", "Superadmin"],
      },
      {
        path: "/admin/eventtype",
        title: "Event Type",
        icon: "bi bi-caret-right",
        className: "",
        extralink: true,
        submenu: [],
        role: ["StaffAdmin", "Superadmin"],
      },

      {
        path: "/admin/facility",
        title: "Facility",
        icon: "bi bi-caret-right",
        className: "",
        extralink: true,
        submenu: [],
        role: ["StaffAdmin", "Superadmin"],
      },
      // {
      // path: "/admin",
      // title: "Incident Master",
      // icon: "bi bi-gear",
      // className: "has-arrow",
      // extralink: true,
      // submenu: [
      //     {
      //       path: "/admin/detectionmethodlist",
      //       title: "Incident Detection Method",
      //       icon: "bi bi-caret-right",
      //       className: "",
      //       extralink: true,
      //       submenu: [],
      //       role: ["StaffAdmin", "Superadmin"],
      //     },
      //     {
      //       path: "/admin/incidenttypelist",
      //       title: "Incident Type",
      //       icon: "bi bi-caret-right",
      //       className: "",
      //       extralink: true,
      //       submenu: [],
      //       role: ["StaffAdmin", "Superadmin"],
      //     },
      //     {
      //       path: "/admin/explosivelist",
      //       title: "Incident Explosive Types",
      //       icon: "bi bi-caret-right",
      //       className: "",
      //       extralink: true,
      //       submenu: [],
      //       role: ["StaffAdmin", "Superadmin"],
      //     },

      //   ], role: ["StaffAdmin", "Superadmin"],
      // },

      {
        path: "/admin/detectionmethodlist",
        title: "INC-Detection Method",
        icon: "bi bi-caret-right",
        className: "",
        extralink: true,
        submenu: [],
        role: ["StaffAdmin", "Superadmin"],
      },
      {
        path: "/admin/disablingList",
        title: "INC-Disabling",
        icon: "bi bi-caret-right",
        className: "",
        extralink: true,
        submenu: [],
        role: ["StaffAdmin", "Superadmin"],
      },
      {
        path: "/admin/explosivelist",
        title: "INC-Explosives",
        icon: "bi bi-caret-right",
        className: "",
        extralink: true,
        submenu: [],
        role: ["StaffAdmin", "Superadmin"],
      },
      {
        path: "/admin/gunslist",
        title: "INC-Guns",
        icon: "bi bi-caret-right",
        className: "",
        extralink: true,
        submenu: [],
        role: ["StaffAdmin", "Superadmin"],
      },
      {
        path: "/admin/incendiariesList",
        title: "INC-Incendiary",
        icon: "bi bi-caret-right",
        className: "",
        extralink: true,
        submenu: [],
        role: ["StaffAdmin", "Superadmin"],
      },
      {
        path: "/admin/incidenttypelist",
        title: "INC-Incident Type",
        icon: "bi bi-caret-right",
        className: "",
        extralink: true,
        submenu: [],
        role: ["StaffAdmin", "Superadmin"],
      },

      {
        path: "/admin/individuallist",
        title: "INC-Individual Type",
        icon: "bi bi-caret-right",
        className: "",
        extralink: true,
        submenu: [],
        role: ["StaffAdmin", "Superadmin"],
      },
      {
        path: "/admin/sharpObjectList",
        title: "INC-Sharp Object",
        icon: "bi bi-caret-right",
        className: "",
        extralink: true,
        submenu: [],
        role: ["StaffAdmin", "Superadmin"],
      },
      {
        path: "/admin/inspectiontypemaster",
        title: "Inspection Category",
        icon: "bi bi-caret-right",
        className: "",
        extralink: true,
        submenu: [],
        role: ["StaffAdmin", "Superadmin"],
      },
      {
        path: "/admin/inspectiontype",
        title: "Inspection Type",
        icon: "bi bi-caret-right",
        className: "",
        extralink: true,
        submenu: [],
        role: ["StaffAdmin", "Superadmin"],
      },
      {
        path: "/admin/referencecategories",
        title: "Reference Categories",
        icon: "bi bi-caret-right",
        className: "",
        extralink: true,
        submenu: [],
        role: ["StaffAdmin", "Superadmin"],
      },

      {
        path: "/admin/user",
        title: "User Management",
        icon: "bi bi-caret-right",
        className: "",
        extralink: true,
        submenu: [],
        role: ["StaffAdmin", "Superadmin"],
      },
      {
        path: "/admin/violationtype",
        title: "Violation Type",
        icon: "bi bi-caret-right",
        className: "",
        extralink: true,
        submenu: [],
        role: ["StaffAdmin", "Superadmin"],
      },
    ],
    role: ["StaffAdmin", "Superadmin"],
  },

  // {
  //   path: "/admin/map",
  //   title: "Map",
  //   icon: "bi bi-map",
  //   className: "",
  //   extralink: true,
  //   submenu: [],
  //   role: ["StaffAdmin", "Superadmin"],
  // },

  // {
  //   path: "/admin/map",
  //   title: "Map",
  //   icon: "bi bi-map",
  //   className: "",
  //   extralink: true,
  //   submenu: [],
  //   role: ["Superadmin"],
  // },
];
